### ISSUE TITLE
mcmod.info is missing information

### ISSUE THREAD

**Issue by HellishINC** [Eladkay/trampling#1]
Currently the mod shows as "Example Mod 1.0" since mcmod.info appears to have been left blank.

**Comment by Eladkay** [comment]
https://github.com/Eladkay/trampling/blob/master/src/main/resources/mcmod.info

**Comment by HellishINC** [comment]
I looked through your source and check that first, but here you go:

http://i.imgur.com/h8yUaap.png

**Comment by Eladkay** [comment]
Yes I'm aware but I'm not going to push an update just for that.
